web:
  image: jbarnes7952/puput_docker
  container_name: blog_wagtail
  volumes:
    - ./static:/app/blog/static
    - ./data/media:/app/blog/media
    - /docker/storage/webfrontend/letsencrypt/www:/var/www/letsencrypt
    - /docker/storage/webfrontend/letsencrypt/etc:/etc/letsencrypt
      #  ports:
      #    - "8090:80"
      #    - "8888:8888"  
      #  command: ./manage.py runserver 0.0.0.0:8000 
  command: gunicorn blog.wsgi:application -b "0.0.0.0:80"
  links:
    - postgres

postgres:
  container_name: blog_postgres
  image: postgres
  environment:
    POSTGRES_PASSWORD: mysecretpassword

nginx:
  build: nginx/
  ports:
    - "8080:80"
    - "443:443"  
  container_name: blog_nginx
  # image: nginx
  links:
    - web
  volumes:
    - ./static:/static
    - ./data/media:/media  

#adminer:
#    image: adminer
    #restart: always
#    ports:
#      - 8081:8080
